/**
 * Generates the HTML boilerplate.
 *
 * @param title - The title of the web page.
 * @returns {string} The raw HTML code.
 */
export const htmlTemplate = (title: string) => `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <h1>Welcome to ${title}</h1>
        <p>Generated by MyGen CLI </p>
        <button id="clickMe">Click me</button>
    </div>
    <script src="script.js"></script>
</body>
</html>
`;